name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        python-version: ['3.6', '3.7', '3.8']

    env:
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}

    runs-on: ${{ format('{0}-latest', matrix.os) }}

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: install dependencies
      run: |
        make install
        pip freeze

    - name: pre-commit all
      run: pre-commit run --all-files

    - name: test
      run: |
        make test
        coverage xml

    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        env_vars: PYTHON,OS
